cache:
  paths:
    - node_modules/
    - dist/

stages:
  - build
  - staging
  - production

build:
  image: node:12
  stage: build
  script:
    - yarn install
    - VUE_APP_YANDEX_KEY=$VUE_APP_YANDEX_KEY yarn build
  artifacts:
    paths:
      - dist

staging:
  stage: staging
  only:
    - master
  image: alpine
  dependencies:
    - build
  before_script:
    - apk add --no-cache rsync openssh
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
    - mkdir -p ~/.ssh
    - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
  script:
    - "rsync -rav --delete --no-perms ./dist/* $SSH_USER@$SSH_HOST:$SSH_PATH"

production:
  stage: production
  dependencies:
    - build
  only:
    - master
  image: alpine
  when: manual
  before_script:
    - apk add --no-cache rsync openssh
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY_PRODUCTION" | tr -d '\r' | ssh-add - > /dev/null
    - mkdir -p ~/.ssh
    - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
  script:
    - "rsync -rav --delete --no-perms ./dist/* $SSH_USER_PRODUCTION@$SSH_HOST_PRODUCTION:$SSH_PATH_PRODUCTION"
